In [1]:
import pandas as pd

In [2]:
skills_dict = {
    "Programming Languages": [
        "python", "java", "c", "c++", "c#", "javascript", "typescript", "go",
        "rust", "ruby", "php", "swift", "kotlin", "scala", "r", "matlab",
        "perl", "dart", "lua", "haskell", "julia", "objective-c", "sql",
        "bash", "shell scripting", "powershell", "assembly", "cobol",
        "fortran", "visual basic",
    ],
    "Web Development - Frontend": [
        "html", "css", "sass", "less", "react", "angular", "vue.js",
        "svelte", "next.js", "nuxt.js", "jquery", "bootstrap",
        "tailwind css", "webpack", "redux", "ember.js", "backbone.js",
    ],
    "Web Development - Backend": [
        "node.js", "express.js", "django", "flask", "fastapi",
        "spring boot", "ruby on rails", "laravel", "asp.net", "nestjs",
        "graphql", "rest api", "soap", "microservices", "grpc",
    ],
    "Databases": [
        "mysql", "postgresql", "sqlite", "mongodb", "redis", "cassandra",
        "oracle", "microsoft sql server", "dynamodb", "elasticsearch",
        "neo4j", "firebase", "mariadb", "couchdb", "snowflake", "bigquery",
    ],
    "Data Science & Machine Learning": [
        "machine learning", "deep learning", "artificial intelligence",
        "natural language processing", "computer vision", "tensorflow",
        "pytorch", "keras", "scikit-learn", "pandas", "numpy",
        "matplotlib", "seaborn", "opencv", "xgboost", "lightgbm", "nltk",
        "spacy", "hugging face transformers", "reinforcement learning",
        "statistics", "data visualization", "feature engineering",
        "model deployment", "mlops",
    ],
    "Data Engineering & Big Data": [
        "apache spark", "hadoop", "kafka", "airflow", "etl",
        "data warehousing", "data pipelines", "dbt", "hive", "flink",
        "presto", "databricks",
    ],
    "Cloud Platforms": [
        "amazon web services", "microsoft azure", "google cloud platform",
        "ibm cloud", "oracle cloud", "heroku", "digitalocean", "cloudflare",
    ],
    "DevOps & CI/CD": [
        "docker", "kubernetes", "jenkins", "github actions",
        "gitlab ci/cd", "terraform", "ansible", "puppet", "chef",
        "ci/cd", "infrastructure as code", "prometheus", "grafana",
        "nginx", "apache",
    ],
    "Mobile Development": [
        "android development", "ios development", "react native",
        "flutter", "xamarin", "ionic",
    ],
    "Testing & QA": [
        "unit testing", "integration testing", "selenium", "pytest",
        "junit", "test-driven development", "cypress", "postman",
        "load testing", "manual testing", "automation testing",
        "qa methodologies",
    ],
    "Version Control & Collaboration": [
        "git", "github", "gitlab", "bitbucket", "svn", "jira",
        "confluence", "trello", "slack", "asana",
    ],
    "Operating Systems": [
        "linux", "windows", "macos", "unix", "ubuntu", "red hat",
    ],
    "Cybersecurity": [
        "network security", "penetration testing", "ethical hacking",
        "encryption", "siem", "firewalls", "vulnerability assessment",
        "owasp", "iso 27001", "security auditing",
    ],
    "Networking": [
        "tcp/ip", "dns", "vpn", "load balancing", "network administration",
        "routing and switching", "http/https",
    ],
    "Design & UI/UX": [
        "figma", "adobe xd", "sketch", "photoshop", "illustrator",
        "ui design", "ux research", "wireframing", "prototyping",
        "user testing",
    ],
    "Project Management & Methodologies": [
        "agile", "scrum", "kanban", "waterfall", "project planning",
        "risk management", "pmp", "six sigma", "product management",
    ],
    "Business & Analytics Tools": [
        "excel", "power bi", "tableau", "google analytics", "sap",
        "salesforce", "looker", "sql server reporting services",
    ],
    "Game Development": [
        "unity", "unreal engine", "game design", "3d modeling", "blender",
        "opengl", "directx",
    ],
    "Embedded Systems & Hardware": [
        "embedded c", "microcontrollers", "arduino", "raspberry pi",
        "rtos", "fpga", "vhdl", "verilog", "iot",
    ],
    "API & Architecture": [
        "rest api", "graphql", "microservices architecture",
        "system design", "design patterns",
        "object-oriented programming", "data structures and algorithms",
    ],
    "Soft Skills": [
        "communication", "teamwork", "leadership", "problem solving",
        "critical thinking", "time management", "adaptability",
        "collaboration", "conflict resolution", "mentoring",
        "presentation skills", "decision making",
    ],
}

In [3]:
import re
import time

# Flatten your skill dictionary
flat_skills = []

for category, skills in skills_dict.items():
    for skill in skills:
        flat_skills.append((category, skill))

def extract_skills_fast(text):
    if pd.isna(text):
        return {}

    text = str(text).lower()
    result = {}

    for category, skill in flat_skills:
        pattern = r"\b" + re.escape(skill.lower()) + r"\b"

        if re.search(pattern, text):
            result.setdefault(category, []).append(skill)

    return result

In [4]:
sample_resume = """
Computer Science student with experience in Python, C++, JavaScript,
React, SQL, MongoDB, Git, machine learning and TensorFlow.
Built machine learning projects and web applications.
"""

resume_skills = extract_skills_fast(sample_resume)

print(resume_skills)

{'Programming Languages': ['python', 'c', 'javascript', 'sql'], 'Web Development - Frontend': ['react'], 'Databases': ['mongodb'], 'Data Science & Machine Learning': ['machine learning', 'tensorflow'], 'Version Control & Collaboration': ['git']}

In [5]:
current_skill_profile = set()

for skills in resume_skills.values():
    for skill in skills:
        current_skill_profile.add(skill.lower().strip())

print("Current Skills:", len(current_skill_profile))
print(sorted(current_skill_profile))

Current Skills: 9
['c', 'git', 'javascript', 'machine learning', 'mongodb', 'python', 'react', 'sql', 'tensorflow']

In [6]:


reliable_role_skill_df = pd.read_csv(
    "../data/req_skill_graph.csv"
)

print(reliable_role_skill_df.shape)
display(reliable_role_skill_df.head())
print(reliable_role_skill_df.columns.tolist())

(4692, 7)

,Unnamed: 0,role,skill,job_count,role_job_count,skill_demand_pct,requirement_level
0,963,Android Developer,java,12,16,75.00,Core
1,964,Android Developer,kotlin,10,16,62.50,Core
2,965,Android Developer,android development,7,16,43.75,Common
3,966,Android Developer,agile,6,16,37.50,Common
4,967,Android Developer,communication,5,16,31.25,Common

['Unnamed: 0', 'role', 'skill', 'job_count', 'role_job_count', 'skill_demand_pct', 'requirement_level']

In [7]:
target_role = "Data Architect"

In [8]:
target_requirements = reliable_role_skill_df[
    reliable_role_skill_df["role"] == target_role
].copy()

print("Target Role :", target_role)
print("Required skills:", len(target_requirements))

display(
    target_requirements[
        ["skill","skill_demand_pct","requirement_level"]
    ].sort_values("skill_demand_pct",ascending=False)
)

Target Role : Data Architect
Required skills: 61

               skill  skill_demand_pct requirement_level
791              sql         75.000000              Core
792              etl         53.571429              Core
793    communication         39.285714            Common
794        snowflake         39.285714            Common
795           python         35.714286            Common
..               ...               ...               ...
847          jenkins          3.571429              Rare
848  problem solving          3.571429              Rare
849            redis          3.571429              Rare
850            ci/cd          3.571429              Rare
851  shell scripting          3.571429              Rare

[61 rows x 3 columns]

In [9]:
current_skills = set(
    skill.lower().strip()
    for skill in current_skill_profile
)

required_skills = set(
    target_requirements["skill"].str.lower().str.strip()
)

matched_skills = current_skills & required_skills
missing_skills = required_skills - current_skills

print("Current skills:", len(current_skills))
print("Required skills:", len(required_skills))
print("Matched skills:", len(matched_skills))
print("Missing skills:", len(missing_skills))

print("\nMATCHED:")
print(sorted(matched_skills))

print("\nMISSING:")
print(sorted(missing_skills))

Current skills: 9
Required skills: 61
Matched skills: 6
Missing skills: 55

MATCHED:
['c', 'git', 'mongodb', 'python', 'react', 'sql']

MISSING:
['agile', 'airflow', 'amazon web services', 'apache', 'apache spark', 'bash', 'bigquery', 'ci/cd', 'collaboration', 'communication', 'critical thinking', 'css', 'data pipelines', 'data visualization', 'data warehousing', 'databricks', 'dbt', 'decision making', 'elasticsearch', 'encryption', 'etl', 'go', 'hadoop', 'java', 'jenkins', 'kafka', 'leadership', 'linux', 'looker', 'mentoring', 'microservices', 'microsoft azure', 'microsoft sql server', 'mysql', 'network security', 'oracle', 'perl', 'postgresql', 'power bi', 'powershell', 'presentation skills', 'presto', 'problem solving', 'r', 'red hat', 'redis', 'redux', 'salesforce', 'sap', 'scala', 'scrum', 'shell scripting', 'snowflake', 'tableau', 'windows']

In [10]:
skill_gap_df = target_requirements[
    ~target_requirements["skill"].str.lower().str.strip().isin(current_skills)
].copy()

skill_gap_df = skill_gap_df[
    [
        "skill", "skill_demand_pct" , "requirement_level"
    ]
].sort_values(
    "skill_demand_pct",
    ascending=False
).reset_index(drop=True)

print("Total missing skills :", len(skill_gap_df))

display(skill_gap_df)

Total missing skills : 55

                   skill  skill_demand_pct requirement_level
0                    etl         53.571429              Core
1          communication         39.285714            Common
2              snowflake         39.285714            Common
3       data warehousing         35.714286            Common
4             databricks         28.571429            Common
5         data pipelines         25.000000            Common
6          collaboration         25.000000            Common
7             leadership         25.000000            Common
8                  agile         25.000000            Common
9               power bi         17.857143        Supporting
10                apache         14.285714        Supporting
11    data visualization         14.285714        Supporting
12                oracle         10.714286        Supporting
13                 kafka         10.714286        Supporting
14                    go         10.714286        Supporting
15            powershell         10.714286        Supporting
16  microsoft sql server         10.714286        Supporting
17              bigquery          7.142857        Supporting
18                hadoop          7.142857        Supporting
19                   dbt          7.142857        Supporting
20         elasticsearch          7.142857        Supporting
21                   css          7.142857        Supporting
22            encryption          7.142857        Supporting
23               airflow          7.142857        Supporting
24                 mysql          7.142857        Supporting
25            salesforce          7.142857        Supporting
26             mentoring          7.142857        Supporting
27                 redux          3.571429              Rare
28       decision making          3.571429              Rare
29                     r          3.571429              Rare
30               tableau          3.571429              Rare
31            postgresql          3.571429              Rare
32     critical thinking          3.571429              Rare
33                 scala          3.571429              Rare
34          apache spark          3.571429              Rare
35                presto          3.571429              Rare
36                  bash          3.571429              Rare
37                  java          3.571429              Rare
38       microsoft azure          3.571429              Rare
39                 scrum          3.571429              Rare
40   amazon web services          3.571429              Rare
41                 linux          3.571429              Rare
42               windows          3.571429              Rare
43               red hat          3.571429              Rare
44      network security          3.571429              Rare
45                   sap          3.571429              Rare
46                looker          3.571429              Rare
47                  perl          3.571429              Rare
48   presentation skills          3.571429              Rare
49         microservices          3.571429              Rare
50               jenkins          3.571429              Rare
51       problem solving          3.571429              Rare
52                 redis          3.571429              Rare
53                 ci/cd          3.571429              Rare
54       shell scripting          3.571429              Rare

In [11]:
critical_gaps = skill_gap_df[
    skill_gap_df["requirement_level"] == "Core"
].copy()

print("Critical skill gaps:", len(critical_gaps))

display(critical_gaps)

Critical skill gaps: 1

  skill  skill_demand_pct requirement_level
0   etl         53.571429              Core

In [12]:
requirement_weights = {
    "Core": 1.00,
    "Common": 0.75,
    "Supporting": 0.50,
    "Rare": 0.25
}

skill_gap_df["requirement_weight"] = (
    skill_gap_df["requirement_level"]
    .map(requirement_weights)
)

skill_gap_df["demand_score"] = (
    skill_gap_df["skill_demand_pct"] / 100
)

skill_gap_df["gap_priority_score"] = (
    skill_gap_df["requirement_weight"]
    * skill_gap_df["demand_score"]
)

skill_gap_df = skill_gap_df.sort_values(
    "gap_priority_score",
    ascending=False
).reset_index(drop=True)

display(skill_gap_df)

,skill,skill_demand_pct,requirement_level,requirement_weight,demand_score,gap_priority_score
0,etl,53.571429,Core,1.00,0.535714,0.535714
1,communication,39.285714,Common,0.75,0.392857,0.294643
2,snowflake,39.285714,Common,0.75,0.392857,0.294643
3,data warehousing,35.714286,Common,0.75,0.357143,0.267857
4,databricks,28.571429,Common,0.75,0.285714,0.214286
5,data pipelines,25.000000,Common,0.75,0.250000,0.187500
6,collaboration,25.000000,Common,0.75,0.250000,0.187500
7,leadership,25.000000,Common,0.75,0.250000,0.187500
8,agile,25.000000,Common,0.75,0.250000,0.187500
9,power bi,17.857143,Supporting,0.50,0.178571,0.089286
10,apache,14.285714,Supporting,0.50,0.142857,0.071429
11,data visualization,14.285714,Supporting,0.50,0.142857,0.071429
12,oracle,10.714286,Supporting,0.50,0.107143,0.053571
13,kafka,10.714286,Supporting,0.50,0.107143,0.053571
14,go,10.714286,Supporting,0.50,0.107143,0.053571
15,powershell,10.714286,Supporting,0.50,0.107143,0.053571
16,microsoft sql server,10.714286,Supporting,0.50,0.107143,0.053571
17,bigquery,7.142857,Supporting,0.50,0.071429,0.035714
18,hadoop,7.142857,Supporting,0.50,0.071429,0.035714
19,dbt,7.142857,Supporting,0.50,0.071429,0.035714
20,elasticsearch,7.142857,Supporting,0.50,0.071429,0.035714
21,css,7.142857,Supporting,0.50,0.071429,0.035714
22,encryption,7.142857,Supporting,0.50,0.071429,0.035714
23,airflow,7.142857,Supporting,0.50,0.071429,0.035714
24,mysql,7.142857,Supporting,0.50,0.071429,0.035714
25,salesforce,7.142857,Supporting,0.50,0.071429,0.035714
26,mentoring,7.142857,Supporting,0.50,0.071429,0.035714
27,redux,3.571429,Rare,0.25,0.035714,0.008929
28,decision making,3.571429,Rare,0.25,0.035714,0.008929
29,r,3.571429,Rare,0.25,0.035714,0.008929
30,tableau,3.571429,Rare,0.25,0.035714,0.008929
31,postgresql,3.571429,Rare,0.25,0.035714,0.008929
32,critical thinking,3.571429,Rare,0.25,0.035714,0.008929
33,scala,3.571429,Rare,0.25,0.035714,0.008929
34,apache spark,3.571429,Rare,0.25,0.035714,0.008929
35,presto,3.571429,Rare,0.25,0.035714,0.008929
36,bash,3.571429,Rare,0.25,0.035714,0.008929
37,java,3.571429,Rare,0.25,0.035714,0.008929
38,microsoft azure,3.571429,Rare,0.25,0.035714,0.008929
39,scrum,3.571429,Rare,0.25,0.035714,0.008929
40,amazon web services,3.571429,Rare,0.25,0.035714,0.008929
41,linux,3.571429,Rare,0.25,0.035714,0.008929
42,windows,3.571429,Rare,0.25,0.035714,0.008929
43,red hat,3.571429,Rare,0.25,0.035714,0.008929
44,network security,3.571429,Rare,0.25,0.035714,0.008929
45,sap,3.571429,Rare,0.25,0.035714,0.008929
46,looker,3.571429,Rare,0.25,0.035714,0.008929
47,perl,3.571429,Rare,0.25,0.035714,0.008929
48,presentation skills,3.571429,Rare,0.25,0.035714,0.008929
49,microservices,3.571429,Rare,0.25,0.035714,0.008929
50,jenkins,3.571429,Rare,0.25,0.035714,0.008929
51,problem solving,3.571429,Rare,0.25,0.035714,0.008929
52,redis,3.571429,Rare,0.25,0.035714,0.008929
53,ci/cd,3.571429,Rare,0.25,0.035714,0.008929
54,shell scripting,3.571429,Rare,0.25,0.035714,0.008929

In [16]:
# Remove previous transferability columns if the cell was partially run
for col in ["role_count", "role_count_x", "role_count_y",
            "transferability_score"]:
    if col in skill_gap_df.columns:
        skill_gap_df.drop(columns=col, inplace=True)


# Count reliable roles requiring each skill
skill_role_counts = (
    reliable_role_skill_df
    .groupby("skill")["role"]
    .nunique()
    .rename("role_count")
)

# Add role count to the gap table
skill_gap_df = skill_gap_df.merge(
    skill_role_counts,
    left_on="skill",
    right_index=True,
    how="left"
)

# Total reliable roles
total_reliable_roles = reliable_role_skill_df["role"].nunique()

# Transferability
skill_gap_df["transferability_score"] = (
    skill_gap_df["role_count"] / total_reliable_roles
)

# Display
display(
    skill_gap_df[
        [
            "skill",
            "role_count",
            "transferability_score",
            "skill_demand_pct",
            "requirement_level",
            "gap_priority_score"
        ]
    ]
)

,skill,role_count,transferability_score,skill_demand_pct,requirement_level,gap_priority_score
0,etl,44,0.325926,53.571429,Core,0.535714
1,communication,122,0.903704,39.285714,Common,0.294643
2,snowflake,30,0.222222,39.285714,Common,0.294643
3,data warehousing,26,0.192593,35.714286,Common,0.267857
4,databricks,30,0.222222,28.571429,Common,0.214286
5,data pipelines,32,0.237037,25.000000,Common,0.187500
6,collaboration,99,0.733333,25.000000,Common,0.187500
7,leadership,84,0.622222,25.000000,Common,0.187500
8,agile,98,0.725926,25.000000,Common,0.187500
9,power bi,35,0.259259,17.857143,Supporting,0.089286
10,apache,25,0.185185,14.285714,Supporting,0.071429
11,data visualization,30,0.222222,14.285714,Supporting,0.071429
12,oracle,49,0.362963,10.714286,Supporting,0.053571
13,kafka,40,0.296296,10.714286,Supporting,0.053571
14,go,68,0.503704,10.714286,Supporting,0.053571
15,powershell,35,0.259259,10.714286,Supporting,0.053571
16,microsoft sql server,16,0.118519,10.714286,Supporting,0.053571
17,bigquery,16,0.118519,7.142857,Supporting,0.035714
18,hadoop,23,0.170370,7.142857,Supporting,0.035714
19,dbt,17,0.125926,7.142857,Supporting,0.035714
20,elasticsearch,11,0.081481,7.142857,Supporting,0.035714
21,css,34,0.251852,7.142857,Supporting,0.035714
22,encryption,31,0.229630,7.142857,Supporting,0.035714
23,airflow,16,0.118519,7.142857,Supporting,0.035714
24,mysql,29,0.214815,7.142857,Supporting,0.035714
25,salesforce,16,0.118519,7.142857,Supporting,0.035714
26,mentoring,48,0.355556,7.142857,Supporting,0.035714
27,redux,9,0.066667,3.571429,Rare,0.008929
28,decision making,22,0.162963,3.571429,Rare,0.008929
29,r,54,0.400000,3.571429,Rare,0.008929
30,tableau,30,0.222222,3.571429,Rare,0.008929
31,postgresql,27,0.200000,3.571429,Rare,0.008929
32,critical thinking,33,0.244444,3.571429,Rare,0.008929
33,scala,34,0.251852,3.571429,Rare,0.008929
34,apache spark,12,0.088889,3.571429,Rare,0.008929
35,presto,6,0.044444,3.571429,Rare,0.008929
36,bash,39,0.288889,3.571429,Rare,0.008929
37,java,88,0.651852,3.571429,Rare,0.008929
38,microsoft azure,38,0.281481,3.571429,Rare,0.008929
39,scrum,60,0.444444,3.571429,Rare,0.008929
40,amazon web services,19,0.140741,3.571429,Rare,0.008929
41,linux,58,0.429630,3.571429,Rare,0.008929
42,windows,46,0.340741,3.571429,Rare,0.008929
43,red hat,8,0.059259,3.571429,Rare,0.008929
44,network security,21,0.155556,3.571429,Rare,0.008929
45,sap,16,0.118519,3.571429,Rare,0.008929
46,looker,7,0.051852,3.571429,Rare,0.008929
47,perl,18,0.133333,3.571429,Rare,0.008929
48,presentation skills,26,0.192593,3.571429,Rare,0.008929
49,microservices,45,0.333333,3.571429,Rare,0.008929
50,jenkins,49,0.362963,3.571429,Rare,0.008929
51,problem solving,52,0.385185,3.571429,Rare,0.008929
52,redis,19,0.140741,3.571429,Rare,0.008929
53,ci/cd,71,0.525926,3.571429,Rare,0.008929
54,shell scripting,24,0.177778,3.571429,Rare,0.008929

In [17]:
display(
    skill_gap_df[
        [
            "skill",
            "skill_demand_pct",
            "requirement_level",
            "gap_priority_score",
            "role_count",
            "transferability_score"
        ]
    ].sort_values(
        "gap_priority_score",
        ascending=False
    )
)

,skill,skill_demand_pct,requirement_level,gap_priority_score,role_count,transferability_score
0,etl,53.571429,Core,0.535714,44,0.325926
1,communication,39.285714,Common,0.294643,122,0.903704
2,snowflake,39.285714,Common,0.294643,30,0.222222
3,data warehousing,35.714286,Common,0.267857,26,0.192593
4,databricks,28.571429,Common,0.214286,30,0.222222
5,data pipelines,25.000000,Common,0.187500,32,0.237037
6,collaboration,25.000000,Common,0.187500,99,0.733333
7,leadership,25.000000,Common,0.187500,84,0.622222
8,agile,25.000000,Common,0.187500,98,0.725926
9,power bi,17.857143,Supporting,0.089286,35,0.259259
10,apache,14.285714,Supporting,0.071429,25,0.185185
11,data visualization,14.285714,Supporting,0.071429,30,0.222222
12,oracle,10.714286,Supporting,0.053571,49,0.362963
13,kafka,10.714286,Supporting,0.053571,40,0.296296
14,go,10.714286,Supporting,0.053571,68,0.503704
15,powershell,10.714286,Supporting,0.053571,35,0.259259
16,microsoft sql server,10.714286,Supporting,0.053571,16,0.118519
17,bigquery,7.142857,Supporting,0.035714,16,0.118519
18,hadoop,7.142857,Supporting,0.035714,23,0.170370
19,dbt,7.142857,Supporting,0.035714,17,0.125926
20,elasticsearch,7.142857,Supporting,0.035714,11,0.081481
21,css,7.142857,Supporting,0.035714,34,0.251852
22,encryption,7.142857,Supporting,0.035714,31,0.229630
23,airflow,7.142857,Supporting,0.035714,16,0.118519
24,mysql,7.142857,Supporting,0.035714,29,0.214815
25,salesforce,7.142857,Supporting,0.035714,16,0.118519
26,mentoring,7.142857,Supporting,0.035714,48,0.355556
27,redux,3.571429,Rare,0.008929,9,0.066667
28,decision making,3.571429,Rare,0.008929,22,0.162963
29,r,3.571429,Rare,0.008929,54,0.400000
30,tableau,3.571429,Rare,0.008929,30,0.222222
31,postgresql,3.571429,Rare,0.008929,27,0.200000
32,critical thinking,3.571429,Rare,0.008929,33,0.244444
33,scala,3.571429,Rare,0.008929,34,0.251852
34,apache spark,3.571429,Rare,0.008929,12,0.088889
35,presto,3.571429,Rare,0.008929,6,0.044444
36,bash,3.571429,Rare,0.008929,39,0.288889
37,java,3.571429,Rare,0.008929,88,0.651852
38,microsoft azure,3.571429,Rare,0.008929,38,0.281481
39,scrum,3.571429,Rare,0.008929,60,0.444444
40,amazon web services,3.571429,Rare,0.008929,19,0.140741
41,linux,3.571429,Rare,0.008929,58,0.429630
42,windows,3.571429,Rare,0.008929,46,0.340741
43,red hat,3.571429,Rare,0.008929,8,0.059259
44,network security,3.571429,Rare,0.008929,21,0.155556
45,sap,3.571429,Rare,0.008929,16,0.118519
46,looker,3.571429,Rare,0.008929,7,0.051852
47,perl,3.571429,Rare,0.008929,18,0.133333
48,presentation skills,3.571429,Rare,0.008929,26,0.192593
49,microservices,3.571429,Rare,0.008929,45,0.333333
50,jenkins,3.571429,Rare,0.008929,49,0.362963
51,problem solving,3.571429,Rare,0.008929,52,0.385185
52,redis,3.571429,Rare,0.008929,19,0.140741
53,ci/cd,3.571429,Rare,0.008929,71,0.525926
54,shell scripting,3.571429,Rare,0.008929,24,0.177778